sudo: false

language: java
jdk:
  - openjdk11

cache:
  directories:
  - '$HOME/.m2/repository'

script:
- mvn dependency:purge-local-repository -DactTransitively=false -DreResolve=false
- mvn clean install -B -U

install: true
